### ISSUE TITLE
win10环境，python3 insights.py login命令报错

### ISSUE THREAD

**Issue by Archer456** [appetizerio/insights.py#6]
```
D:\Appetizer\insights.py>git pull
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 4), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/appetizerio/insights.py
   fd5cc02..2599e57  master     -> origin/master
Updating fd5cc02..2599e57
Fast-forward
 insights.py | 2 ++
 1 file changed, 2 insertions(+)


D:\Appetizer\insights.py>python3 insights.py login name password
Traceback (most recent call last):
  File "insights.py", line 404, in <module>
    sys.exit(main())
  File "insights.py", line 400, in main
    return args.func(args)
  File "insights.py", line 97, in login
    }, verify=False)
  File "D:\Python36\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "D:\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "D:\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\Python36\lib\site-packages\urllib3\util\connection.py", line 51, in create_connection
    if host.startswith('['):
AttributeError: 'NoneType' object has no attribute 'startswith'`
```
linux平台ubunut16.04.2  该命令正常 也是Git pull下来的同版本insghts.py

**Comment by Archer456** [comment]
该登录问题已经确认，是由于windows系统 注册表一个键值引起的。
大家可如下解决：
win+R 输入regedit 回车打开注册表
找到 计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings
该位置下 找到ProxyEnable  并删除掉。然后关掉注册表。
在操作注册表前，请利用导出功能备份注册表。以防误操作或操作不当引发其他系统故障后可恢复。

在尝试命令登录python3 insights.py login 账号 密码
![image](https://user-images.githubusercontent.com/18392901/32427535-e1bbcd06-c2fb-11e7-8352-60fef5952f54.png)

便可成功登录了。

**Comment by mingyuan-xia** [comment]
寻寻觅觅好久才找到的，这是一个requests的问题，该库在windows上会读取环境变量（HTTP_PROXY）获取代理信息，如果为空，还会继续从注册表中获得 `ProxyEnable` 这个变量，由于类型不对，导致后继全错，异常抛出点不够明显。已经提交request的issue: https://github.com/requests/requests/issues/4373

原贴：https://stackoverflow.com/questions/46260169/python-locationvalueerror-no-host-specified
https://github.com/conda/conda/issues/3962
